# The behavior of RuboCop can be controlled via the .rubocop.yml
# configuration file. It makes it possible to enable/disable
# certain cops (checks) and to alter their behavior if they accept
# any parameters. The file can be placed either in your home
# directory or in some project directory.
#
# RuboCop will start looking for the configuration file in the directory
# where the inspected file is and continue its way up to the root directory.
#
# See https://docs.rubocop.org/rubocop/configuration



AllCops:
  TargetRubyVersion: 2.4

require:
  - rubocop-performance
  - rubocop-minitest

Style/Documentation:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

# https://docs.rubocop.org/rubocop/cops_layout.html#layoutemptylinesaroundattributeaccessor
Layout/EmptyLinesAroundAttributeAccessor:
  Enabled: true

# https://docs.rubocop.org/rubocop/cops_layout.html#layoutspacearoundmethodcalloperator
Layout/SpaceAroundMethodCallOperator:
  Enabled: true

# https://docs.rubocop.org/rubocop/cops_lint.html#lintdeprecatedopensslconstant
Lint/DeprecatedOpenSSLConstant:
  Enabled: true

# https://docs.rubocop.org/rubocop/cops_lint.html#lintmixedregexpcapturetypes
Lint/MixedRegexpCaptureTypes:
  Enabled: true

# https://docs.rubocop.org/rubocop/cops_lint.html#lintraiseexception
Lint/RaiseException:
  Enabled: true

# https://docs.rubocop.org/rubocop/cops_lint.html#lintstructnewoverride
Lint/StructNewOverride:
  Enabled: true

# https://docs.rubocop.org/rubocop/cops_style.html#styleexponentialnotation
Style/ExponentialNotation:
  Enabled: false

# https://docs.rubocop.org/rubocop/cops_style.html#stylehasheachmethods
Style/HashEachMethods:
  Enabled: true

# https://docs.rubocop.org/rubocop/cops_style.html#stylehashtransformkeys
Style/HashTransformKeys:
  Enabled: true

# https://docs.rubocop.org/rubocop/cops_style.html#stylehashtransformvalues
Style/HashTransformValues:
  Enabled: true

# https://docs.rubocop.org/rubocop/cops_style.html#styleredundantfetchblock
Style/RedundantFetchBlock:
  Enabled: true

# https://docs.rubocop.org/rubocop/cops_style.html#styleredundantregexpcharacterclass
Style/RedundantRegexpCharacterClass:
  Enabled: true

# https://docs.rubocop.org/rubocop/cops_style.html#styleredundantregexpescape
Style/RedundantRegexpEscape:
  Enabled: true

# https://docs.rubocop.org/rubocop/cops_style.html#styleslicingwithrange
Style/SlicingWithRange:
  Enabled: true

# https://docs.rubocop.org/rubocop/cops_lint.html#lintbinaryoperatorwithidenticaloperands
Lint/BinaryOperatorWithIdenticalOperands:
  Enabled: true

# https://docs.rubocop.org/rubocop/cops_lint.html#lintduplicateelsifcondition
Lint/DuplicateElsifCondition:
  Enabled: true

# https://docs.rubocop.org/rubocop/cops_lint.html#lintduplicaterescueexception
Lint/DuplicateRescueException:
  Enabled: true

# https://docs.rubocop.org/rubocop/cops_lint.html#lintemptyconditionalbody
Lint/EmptyConditionalBody:
  Enabled: true

# https://docs.rubocop.org/rubocop/cops_lint.html#lintfloatcomparison
Lint/FloatComparison:
  Enabled: false

# https://docs.rubocop.org/rubocop/cops_lint.html#lintmissingsuper
Lint/MissingSuper:
  Enabled: false

# https://docs.rubocop.org/rubocop/cops_lint.html#lintoutofrangeregexpref
Lint/OutOfRangeRegexpRef:
  Enabled: true

# https://docs.rubocop.org/rubocop/cops_lint.html#lintselfassignment
Lint/SelfAssignment:
  Enabled: true

# https://docs.rubocop.org/rubocop/cops_lint.html#linttoplevelreturnwithargument
Lint/TopLevelReturnWithArgument:
  Enabled: true

# https://docs.rubocop.org/rubocop/cops_lint.html#lintunreachableloop
Lint/UnreachableLoop:
  Enabled: true

# https://docs.rubocop.org/rubocop/cops_style.html#styleaccessorgrouping
Style/AccessorGrouping:
  Enabled: true

# https://docs.rubocop.org/rubocop/cops_style.html#stylearraycoercion
Style/ArrayCoercion:
  Enabled: true

# https://docs.rubocop.org/rubocop/cops_style.html#stylebisectedattraccessor
Style/BisectedAttrAccessor:
  Enabled: true

# https://docs.rubocop.org/rubocop/cops_style.html#stylecaselikeif
Style/CaseLikeIf:
  Enabled: true

# https://docs.rubocop.org/rubocop/cops_style.html#styleexplicitblockargument
Style/ExplicitBlockArgument:
  Enabled: true

# https://docs.rubocop.org/rubocop/cops_style.html#styleglobalstdstream
Style/GlobalStdStream:
  Enabled: false

# https://docs.rubocop.org/rubocop/cops_style.html#stylehashaslastarrayitem
Style/HashAsLastArrayItem:
  Enabled: true

# https://docs.rubocop.org/rubocop/cops_style.html#stylehashlikecase
Style/HashLikeCase:
  Enabled: true

# https://docs.rubocop.org/rubocop/cops_style.html#styleoptionalbooleanparameter
Style/OptionalBooleanParameter:
  Enabled: true

# https://docs.rubocop.org/rubocop/cops_style.html#styleredundantassignment
Style/RedundantAssignment:
  Enabled: true

# https://docs.rubocop.org/rubocop/cops_style.html#styleredundantfileextensioninrequire
Style/RedundantFileExtensionInRequire:
  Enabled: true

# https://docs.rubocop.org/rubocop/cops_style.html#stylesingleargumentdig
Style/SingleArgumentDig:
  Enabled: true

# https://docs.rubocop.org/rubocop/cops_style.html#stylestringconcatenation
Style/StringConcatenation:
  Enabled: true

# https://docs.rubocop.org/rubocop-performance/cops_performance.html#performanceancestorsinclude
Performance/AncestorsInclude:
  Enabled: true

# https://docs.rubocop.org/rubocop-performance/cops_performance.html#performancebigdecimalwithnumericargument
Performance/BigDecimalWithNumericArgument:
  Enabled: true

# https://docs.rubocop.org/rubocop-performance/cops_performance.html#performanceredundantsortblock
Performance/RedundantSortBlock:
  Enabled: true

# https://docs.rubocop.org/rubocop-performance/cops_performance.html#performanceredundantstringchars
Performance/RedundantStringChars:
  Enabled: true

# https://docs.rubocop.org/rubocop-performance/cops_performance.html#performancereversefirst
Performance/ReverseFirst:
  Enabled: true

# https://docs.rubocop.org/rubocop-performance/cops_performance.html#performancesortreverse
Performance/SortReverse:
  Enabled: true

# https://docs.rubocop.org/rubocop-performance/cops_performance.html#performancesqueeze
Performance/Squeeze:
  Enabled: true

# https://docs.rubocop.org/rubocop-performance/cops_performance.html#performancestringinclude
Performance/StringInclude:
  Enabled: true

# https://docs.rubocop.org/rubocop-minitest/cops_minitest.html#minitestassertindelta
Minitest/AssertInDelta:
  Enabled: true

# https://docs.rubocop.org/rubocop-minitest/cops_minitest.html#minitestassertioninlifecyclehook
Minitest/AssertionInLifecycleHook:
  Enabled: true

# https://docs.rubocop.org/rubocop-minitest/cops_minitest.html#minitestassertkindof
Minitest/AssertKindOf:
  Enabled: true

# https://docs.rubocop.org/rubocop-minitest/cops_minitest.html#minitestassertoutput
Minitest/AssertOutput:
  Enabled: true

# https://docs.rubocop.org/rubocop-minitest/cops_minitest.html#minitestassertpathexists
Minitest/AssertPathExists:
  Enabled: true

# https://docs.rubocop.org/rubocop-minitest/cops_minitest.html#minitestassertsilent
Minitest/AssertSilent:
  Enabled: true

# https://docs.rubocop.org/rubocop-minitest/cops_minitest.html#minitestliteralasactualargument
Minitest/LiteralAsActualArgument:
  Enabled: true

# https://docs.rubocop.org/rubocop-minitest/cops_minitest.html#minitestmultipleassertions
Minitest/MultipleAssertions:
  Enabled: false

# https://docs.rubocop.org/rubocop-minitest/cops_minitest.html#minitestrefuteindelta
Minitest/RefuteInDelta:
  Enabled: true

# https://docs.rubocop.org/rubocop-minitest/cops_minitest.html#minitestrefutekindof
Minitest/RefuteKindOf:
  Enabled: true

# https://docs.rubocop.org/rubocop-minitest/cops_minitest.html#minitestrefutepathexists
Minitest/RefutePathExists:
  Enabled: true

# https://docs.rubocop.org/rubocop-minitest/cops_minitest.html#minitesttestmethodname
Minitest/TestMethodName:
  Enabled: true

# https://docs.rubocop.org/rubocop-minitest/cops_minitest.html#minitestunspecifiedexception
Minitest/UnspecifiedException:
  Enabled: true

Layout/BeginEndAlignment: # (new in 0.91)
  Enabled: true
Lint/ConstantDefinitionInBlock: # (new in 0.91)
  Enabled: true
Lint/DuplicateRequire: # (new in 0.90)
  Enabled: true
Lint/EmptyFile: # (new in 0.90)
  Enabled: true
Lint/IdentityComparison: # (new in 0.91)
  Enabled: true
Lint/TrailingCommaInAttributeDeclaration: # (new in 0.90)
  Enabled: true
Lint/UselessMethodDefinition: # (new in 0.90)
  Enabled: true
Lint/UselessTimes: # (new in 0.91)
  Enabled: true
Style/CombinableLoops: # (new in 0.90)
  Enabled: true
Style/KeywordParametersOrder: # (new in 0.90)
  Enabled: true
Style/RedundantSelfAssignment: # (new in 0.90)
  Enabled: true
Style/SoleNestedConditional: # (new in 0.89)
  Enabled: true
Performance/Sum: # (new in 1.8)
  Enabled: true
Lint/HashCompareByIdentity: # (new in 0.93)
  Enabled: true
Lint/RedundantSafeNavigation: # (new in 0.93)
  Enabled: true
Style/ClassEqualityComparison: # (new in 0.93)
  Enabled: true

