#!/usr/bin/env ruby
# frozen_string_literal: true

# require 'bundler/setup'

$LOAD_PATH.unshift("#{__dir__}/../lib")

require 'rubocop_config_updater'

cli = RuboCopConfigUpdater::CLI.new
cli.run(ARGV)
